name: Build
on:
   push:
     branches: [ 'main' ]
     paths-ignore: [ 'docs/**' ]

permissions: write-all

env:
  CONFIG: Release
  SLN_FILE: FSharp.Maui.WinUICompat.NoSamples.sln

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Read last version from CHANGELOG.md
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        path: ./CHANGELOG.md
    - name: Set nightly version
      run: |
        $env:NIGHTLY_VERSION = "${{ steps.changelog_reader.outputs.version }}-nightly-$env:GITHUB_RUN_ID"
        echo "Nightly version is $env:NIGHTLY_VERSION"
        echo "NIGHTLY_VERSION=$env:NIGHTLY_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore $env:SLN_FILE
    - name: Build
      run: dotnet build $env:SLN_FILE -p:Version=$env:NIGHTLY_VERSION -c $env:CONFIG --no-restore
    - name: Pack
      run: dotnet pack $env:SLN_FILE -p:Version=$env:NIGHTLY_VERSION -c $env:CONFIG --no-build --property PackageOutputPath=${PWD}/nupkgs
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: nupkgs/
    - name: Push
      run: dotnet nuget push "nupkgs\*.nupkg" -s https://nuget.pkg.github.com/fabulous-dev/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate