name: Pull Request
on: pull_request

env:
  CONFIG: Release
  SLN_FILE: FSharp.Maui.WinUICompat.NoSamples.sln

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore $env:SLN_FILE
    - name: Build
      run: dotnet build $env:SLN_FILE -c $env:CONFIG --no-restore